ims/cashflow/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('',views.index, name='index' ),
        ]

ims/ims/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('cashflow/', include('cashflow.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]

ims/login/urls.py
from django.urls import path
from . import views

app_name='login'

urlpatterns=[
        path('',views.login, name='login'),
        path('login', views.login_click, name='login_click'),
        path('signup', views.signup, name='signup'),
        ]

ims/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns=[
        path('login/', include('login.urls')),
        path('admin/',admin.site.urls ),
        ]

ims/cashflow/models.py
from django.db import models
from django.utils import timezone
class Dealer(models.Model):
    dealer_name= models.CharField(max_length=100)



class Sale(models.Model):
    date= timezone.now()
    transaction=models.IntegerField(default=0)
    dealer = models.ForeignKey(Dealer , on_delete = models.CASCADE)
class Purchase(models.Model):
    date= timezone.now()
    transaction=models.ForeignKey(Dealer, on_delete=models.CASCADE)




# Create your models here.

ims/login/models.py
from django.db import models


class Credentials(models.Model):
    username= models.CharField(max_length=20)
    password = models.CharField(max_length=15)


# Create your models here.

ims/cashflow/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    
    return render(request, 'index.html' )


# Create your views here.

ims/login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Credentials

def login(request):
    
    return render(request, 'login.html', {'message':message})
def signup(request):
    return render(request, 'login.html', {'message':messaage})
def login_click(request):
    return render(request,'login.html',{'message':message})
# Create your views here.

ims/login/templates/ims/login.html
<html>
    <head><title>Login Page</title></head>
    <body>
        <h1>Welcome to the login Page...</h1>
        <form  method="post">
            <input type="text" name="username" id=username >
            <label for "username">UserName:</label>
            <input type="password" name="password"  id="password">
            <label for="password">Password:</label>
            <input type ="submit" value ="LOGIN"  name="LOGIN" id="LOGIN" formaction="{% url 'login:login_click%' }">
            <input type ="submit" value="SIGN UP" name= "SIGN UP" id="SIGN UP" formaction="{% url 'login:signup' %}">
        </form>
    </body>
</html>